from flask import Flask, render_template, jsonify, request
from flask_socketio import SocketIO, emit
import threading
import time
import requests
from monitor import ResourceMonitor
from anomaly_detector import AnomalyDetector
from disk_analyzer import DiskAnalyzer

app = Flask(__name__)
app.config['SECRET_KEY'] = 'system-monitor-secret'
socketio = SocketIO(app, cors_allowed_origins="*")

# Groq API Configuration
import os
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')  # Set via environment variable
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

monitor = ResourceMonitor()
detector = AnomalyDetector(window_size=100, learning_period=30)
# Optimized for full drive scanning: depth 3 for better coverage, 50MB minimum to focus on large directories
disk_analyzer = DiskAnalyzer(scan_depth=3, min_size_mb=50, recent_hours=24)
monitoring_active = False
anomaly_history = []
last_anomaly_time = 0  # Track last anomaly to prevent spam
disk_scan_in_progress = False

@app.route('/')
def index():
    return render_template('index-premium.html')

@app.route('/api/stats')
def get_stats():
    """Get current system statistics"""
    metrics = monitor.collect_metrics()
    top_processes = monitor.get_top_processes(10)
    
    return jsonify({
        'metrics': metrics,
        'processes': top_processes,
        'is_trained': detector.is_trained,
        'baseline': detector.baseline_stats if detector.is_trained else None,
        'anomaly_count': len(anomaly_history)
    })

@app.route('/api/export', methods=['POST'])
def export_report():
    """Export system report via email or SMS"""
    try:
        data = request.json
        export_type = data.get('type', 'email')
        
        # Gather system data
        metrics = monitor.collect_metrics()
        
        report = f"""
ADAPTIVE SYSTEM MONITOR REPORT
Generated: {metrics['timestamp']}

CURRENT STATUS:
- CPU Usage: {metrics['cpu_percent']:.1f}%
- Memory Usage: {metrics['memory_percent']:.1f}%
- CPU Cores: {metrics['cpu_count']}
- Memory: {metrics['memory_used_mb']/1024:.1f} GB / {metrics['memory_total_mb']/1024:.1f} GB

NETWORK ACTIVITY:
- Upload: {metrics['net_sent_mbps']:.2f} MB/s
- Download: {metrics['net_recv_mbps']:.2f} MB/s

DISK I/O:
- Read: {metrics['disk_read_mbps']:.2f} MB/s
- Write: {metrics['disk_write_mbps']:.2f} MB/s

AI MONITORING:
- Model Status: {'Trained' if detector.is_trained else 'Learning'}
- Anomalies Detected: {len(anomaly_history)}
- Prevention Methods: 20 Active

This report was generated by Adaptive System Monitor with AI-powered anomaly detection.
        """
        
        if export_type == 'email':
            email = data.get('email')
            # In production, integrate with email service (SendGrid, AWS SES, etc.)
            print(f"Would send email to: {email}")
            print(report)
            return jsonify({'message': f'Report sent to {email}', 'success': True})
        
        elif export_type == 'sms':
            phone = data.get('phone')
            # In production, integrate with SMS service (Twilio, AWS SNS, etc.)
            print(f"Would send SMS to: {phone}")
            summary = f"System Monitor: CPU {metrics['cpu_percent']:.1f}%, Memory {metrics['memory_percent']:.1f}%, {len(anomaly_history)} anomalies detected"
            print(summary)
            return jsonify({'message': f'SMS sent to {phone}', 'success': True})
            
    except Exception as e:
        print(f"Export error: {e}")
        return jsonify({'message': 'Failed to send report', 'success': False}), 500

@app.route('/api/disk/overview')
def get_disk_overview():
    """Get disk usage overview"""
    try:
        overview = disk_analyzer.get_disk_overview()
        return jsonify(overview)
    except Exception as e:
        print(f"Disk overview error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/disk/scan', methods=['POST'])
def trigger_disk_scan():
    """Trigger asynchronous filesystem scan (non-blocking)"""
    global disk_scan_in_progress
    
    if disk_scan_in_progress or disk_analyzer.scan_in_progress:
        return jsonify({'message': 'Scan already in progress', 'success': False}), 400
    
    try:
        data = request.json or {}
        root_path = data.get('path', None)
        
        # If no path specified, scan from drive root for full coverage
        if root_path is None:
            import os
            import platform
            
            if platform.system() == 'Windows':
                # Get the drive letter of current directory (usually C:\)
                current_drive = os.path.splitdrive(os.getcwd())[0]
                root_path = current_drive + '\\'  # e.g., 'C:\\'
            else:
                # On Unix/Linux/Mac, scan from root
                root_path = '/'
        
        disk_scan_in_progress = True
        
        print(f"Starting full drive scan from: {root_path}")
        print("This may take a few minutes on first scan...")
        
        # Callback when scan completes
        def scan_complete_callback(result):
            global disk_scan_in_progress
            disk_scan_in_progress = False
            print(f"Full drive scan completed: {len(result)} directories tracked")
        
        # Use async scan for non-blocking operation
        success = disk_analyzer.scan_filesystem_async(root_path, scan_complete_callback)
        
        if not success:
            disk_scan_in_progress = False
            return jsonify({'message': 'Failed to start scan', 'success': False}), 500
        
        return jsonify({
            'message': 'Full drive scan started (async)', 
            'success': True,
            'scan_path': root_path
        })
    except Exception as e:
        disk_scan_in_progress = False
        print(f"Disk scan error: {e}")
        return jsonify({'message': 'Failed to start scan', 'success': False}), 500

@app.route('/api/disk/root-cause')
def get_root_cause_analysis():
    """Get root cause analysis for anomalies"""
    try:
        top_dirs = disk_analyzer.get_top_directories(5)
        
        # Format response with severity levels
        results = []
        for dir_info in top_dirs:
            severity = 'high' if dir_info['impact_score'] > 0.8 else 'medium' if dir_info['impact_score'] > 0.5 else 'low'
            results.append({
                **dir_info,
                'severity': severity,
                'total_size_formatted': disk_analyzer.format_size(dir_info['total_size']),
                'size_delta_formatted': disk_analyzer.format_size(abs(dir_info['size_delta']))
            })
        
        return jsonify({
            'directories': results,
            'scan_available': len(disk_analyzer.current_snapshot) > 0
        })
    except Exception as e:
        print(f"Root cause analysis error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/disk/growing')
def get_fastest_growing():
    """Get fastest growing directories"""
    try:
        growing = disk_analyzer.get_fastest_growing(5)
        
        results = []
        for dir_info in growing:
            results.append({
                **dir_info,
                'total_size_formatted': disk_analyzer.format_size(dir_info['total_size']),
                'size_delta_formatted': disk_analyzer.format_size(dir_info['size_delta'])
            })
        
        return jsonify({'directories': results})
    except Exception as e:
        print(f"Growing directories error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/disk/active')
def get_most_active():
    """Get most recently modified directories"""
    try:
        active = disk_analyzer.get_most_active(5)
        
        results = []
        for dir_info in active:
            results.append({
                **dir_info,
                'total_size_formatted': disk_analyzer.format_size(dir_info['total_size'])
            })
        
        return jsonify({'directories': results})
    except Exception as e:
        print(f"Active directories error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/disk/drives')
def get_all_drives():
    """Get all available drives on the system"""
    try:
        import psutil
        import platform
        
        drives = []
        
        if platform.system() == 'Windows':
            # Get all disk partitions on Windows
            for partition in psutil.disk_partitions():
                try:
                    usage = psutil.disk_usage(partition.mountpoint)
                    drives.append({
                        'path': partition.mountpoint,
                        'name': partition.device,
                        'total_size': usage.total,
                        'used_size': usage.used,
                        'free_size': usage.free,
                        'usage_percent': usage.percent,
                        'total_size_formatted': disk_analyzer.format_size(usage.total),
                        'used_size_formatted': disk_analyzer.format_size(usage.used)
                    })
                except (PermissionError, OSError):
                    continue
        else:
            # Unix/Linux/Mac
            for partition in psutil.disk_partitions():
                if partition.fstype:
                    try:
                        usage = psutil.disk_usage(partition.mountpoint)
                        drives.append({
                            'path': partition.mountpoint,
                            'name': partition.mountpoint,
                            'total_size': usage.total,
                            'used_size': usage.used,
                            'free_size': usage.free,
                            'usage_percent': usage.percent,
                            'total_size_formatted': disk_analyzer.format_size(usage.total),
                            'used_size_formatted': disk_analyzer.format_size(usage.used)
                        })
                    except (PermissionError, OSError):
                        continue
        
        return jsonify({'drives': drives})
    except Exception as e:
        print(f"Get drives error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/disk/treemap')
def get_treemap_data():
    """Get directory tree data for treemap visualization - full recursive scan for accuracy"""
    try:
        import os as _os
        path = request.args.get('path', None)

        if not path:
            return jsonify({'error': 'Path parameter required'}), 400

        path_normalized = _os.path.normpath(path)

        if not _os.path.isdir(path_normalized):
            return jsonify({'directories': [], 'path': path})

        def get_dir_size(dir_path):
            """Fully recursive directory size calculation"""
            total_size = 0
            file_count = 0
            stack = [dir_path]
            while stack:
                current = stack.pop()
                try:
                    for entry in _os.scandir(current):
                        try:
                            if entry.is_file(follow_symlinks=False):
                                total_size += entry.stat(follow_symlinks=False).st_size
                                file_count += 1
                            elif entry.is_dir(follow_symlinks=False):
                                stack.append(entry.path)
                        except (PermissionError, OSError):
                            continue
                except (PermissionError, OSError):
                    continue
            return total_size, file_count

        children = []

        try:
            entries = list(_os.scandir(path_normalized))
        except PermissionError:
            return jsonify({'directories': [], 'path': path})

        for entry in entries:
            if not entry.is_dir(follow_symlinks=False):
                continue
            try:
                total_size, file_count = get_dir_size(entry.path)
                children.append({
                    'path': entry.path,
                    'name': entry.name,
                    'size': total_size,
                    'size_formatted': disk_analyzer.format_size(total_size),
                    'file_count': file_count
                })
            except (PermissionError, OSError):
                continue

        # Filter zero-size and sort by size descending
        children = [c for c in children if c['size'] > 0]
        children.sort(key=lambda x: x['size'], reverse=True)

        return jsonify({
            'path': path,
            'directories': children
        })
    except Exception as e:
        print(f"Treemap data error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/disk/performance')
def get_disk_performance():
    """Get disk analyzer performance statistics"""
    try:
        stats = disk_analyzer.get_performance_stats()
        return jsonify(stats)
    except Exception as e:
        print(f"Performance stats error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/chat', methods=['POST'])
def chat():
    """Handle chatbot requests with Groq API"""
    try:
        data = request.json
        user_message = data.get('message', '')
        context = data.get('context', '')
        
        # Call Groq API
        headers = {
            'Authorization': f'Bearer {GROQ_API_KEY}',
            'Content-Type': 'application/json'
        }
        
        payload = {
            'model': 'mixtral-8x7b-32768',
            'messages': [
                {
                    'role': 'system',
                    'content': f'You are a helpful system monitoring assistant. {context}. Provide concise, helpful responses about system performance.'
                },
                {
                    'role': 'user',
                    'content': user_message
                }
            ],
            'temperature': 0.7,
            'max_tokens': 200
        }
        
        response = requests.post(GROQ_API_URL, headers=headers, json=payload, timeout=10)
        
        if response.status_code == 200:
            result = response.json()
            ai_response = result['choices'][0]['message']['content']
            return jsonify({'response': ai_response})
        else:
            return jsonify({'response': 'I apologize, but I am having trouble connecting to my AI service. Please try again.'}), 200
            
    except Exception as e:
        print(f"Groq API error: {e}")
        return jsonify({'response': 'I encountered an error. Please try asking again.'}), 200

def monitoring_loop():
    """Background monitoring loop"""
    global monitoring_active, anomaly_history, last_anomaly_time
    
    while monitoring_active:
        metrics = monitor.collect_metrics()
        detector.add_sample(metrics)
        anomaly = detector.detect(metrics)
        
        data = {
            'metrics': metrics,
            'anomaly': None,  # Don't send anomaly every time
            'is_trained': detector.is_trained,
            'baseline': detector.baseline_stats if detector.is_trained else None,
            'sample_count': detector.sample_count,
            'learning_period': detector.learning_period
        }
        
        # Anomaly detection disabled - only count them silently
        if anomaly:
            current_time = time.time()
            if current_time - last_anomaly_time > 30:  # 30 second cooldown
                anomaly_history.append(anomaly)
                # Don't send anomaly to frontend - just count it
                # data['anomaly'] = anomaly
                data['anomaly_history'] = anomaly_history[-10:]
                last_anomaly_time = current_time
        
        socketio.emit('update', data)
        time.sleep(1)

@socketio.on('connect')
def handle_connect():
    print('Client connected')
    emit('status', {'monitoring': monitoring_active})

@socketio.on('start_monitoring')
def handle_start():
    global monitoring_active
    if not monitoring_active:
        monitoring_active = True
        thread = threading.Thread(target=monitoring_loop, daemon=True)
        thread.start()
        emit('status', {'monitoring': True}, broadcast=True)

@socketio.on('stop_monitoring')
def handle_stop():
    global monitoring_active
    monitoring_active = False
    emit('status', {'monitoring': False}, broadcast=True)

if __name__ == '__main__':
    socketio.run(app, debug=True, host='0.0.0.0', port=5000)
