from flask import Flask, render_template, jsonify, request
from flask_socketio import SocketIO, emit
import threading
import time
import requests
from monitor import ResourceMonitor
from anomaly_detector import AnomalyDetector

app = Flask(__name__)
app.config['SECRET_KEY'] = 'system-monitor-secret'
socketio = SocketIO(app, cors_allowed_origins="*")

# Groq API Configuration
import os
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')  # Set via environment variable
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

monitor = ResourceMonitor()
detector = AnomalyDetector(window_size=100, learning_period=30)
monitoring_active = False
anomaly_history = []
last_anomaly_time = 0  # Track last anomaly to prevent spam

@app.route('/')
def index():
    return render_template('index-premium.html')

@app.route('/api/stats')
def get_stats():
    """Get current system statistics"""
    metrics = monitor.collect_metrics()
    top_processes = monitor.get_top_processes(10)
    
    return jsonify({
        'metrics': metrics,
        'processes': top_processes,
        'is_trained': detector.is_trained,
        'baseline': detector.baseline_stats if detector.is_trained else None,
        'anomaly_count': len(anomaly_history)
    })

@app.route('/api/export', methods=['POST'])
def export_report():
    """Export system report via email or SMS"""
    try:
        data = request.json
        export_type = data.get('type', 'email')
        
        # Gather system data
        metrics = monitor.collect_metrics()
        
        report = f"""
ADAPTIVE SYSTEM MONITOR REPORT
Generated: {metrics['timestamp']}

CURRENT STATUS:
- CPU Usage: {metrics['cpu_percent']:.1f}%
- Memory Usage: {metrics['memory_percent']:.1f}%
- CPU Cores: {metrics['cpu_count']}
- Memory: {metrics['memory_used_mb']/1024:.1f} GB / {metrics['memory_total_mb']/1024:.1f} GB

NETWORK ACTIVITY:
- Upload: {metrics['net_sent_mbps']:.2f} MB/s
- Download: {metrics['net_recv_mbps']:.2f} MB/s

DISK I/O:
- Read: {metrics['disk_read_mbps']:.2f} MB/s
- Write: {metrics['disk_write_mbps']:.2f} MB/s

AI MONITORING:
- Model Status: {'Trained' if detector.is_trained else 'Learning'}
- Anomalies Detected: {len(anomaly_history)}
- Prevention Methods: 20 Active

This report was generated by Adaptive System Monitor with AI-powered anomaly detection.
        """
        
        if export_type == 'email':
            email = data.get('email')
            # In production, integrate with email service (SendGrid, AWS SES, etc.)
            print(f"Would send email to: {email}")
            print(report)
            return jsonify({'message': f'Report sent to {email}', 'success': True})
        
        elif export_type == 'sms':
            phone = data.get('phone')
            # In production, integrate with SMS service (Twilio, AWS SNS, etc.)
            print(f"Would send SMS to: {phone}")
            summary = f"System Monitor: CPU {metrics['cpu_percent']:.1f}%, Memory {metrics['memory_percent']:.1f}%, {len(anomaly_history)} anomalies detected"
            print(summary)
            return jsonify({'message': f'SMS sent to {phone}', 'success': True})
            
    except Exception as e:
        print(f"Export error: {e}")
        return jsonify({'message': 'Failed to send report', 'success': False}), 500
def chat():
    """Handle chatbot requests with Groq API"""
    try:
        data = request.json
        user_message = data.get('message', '')
        context = data.get('context', '')
        
        # Call Groq API
        headers = {
            'Authorization': f'Bearer {GROQ_API_KEY}',
            'Content-Type': 'application/json'
        }
        
        payload = {
            'model': 'mixtral-8x7b-32768',
            'messages': [
                {
                    'role': 'system',
                    'content': f'You are a helpful system monitoring assistant. {context}. Provide concise, helpful responses about system performance.'
                },
                {
                    'role': 'user',
                    'content': user_message
                }
            ],
            'temperature': 0.7,
            'max_tokens': 200
        }
        
        response = requests.post(GROQ_API_URL, headers=headers, json=payload, timeout=10)
        
        if response.status_code == 200:
            result = response.json()
            ai_response = result['choices'][0]['message']['content']
            return jsonify({'response': ai_response})
        else:
            return jsonify({'response': 'I apologize, but I am having trouble connecting to my AI service. Please try again.'}), 200
            
    except Exception as e:
        print(f"Groq API error: {e}")
        return jsonify({'response': 'I encountered an error. Please try asking again.'}), 200

def monitoring_loop():
    """Background monitoring loop"""
    global monitoring_active, anomaly_history, last_anomaly_time
    
    while monitoring_active:
        metrics = monitor.collect_metrics()
        detector.add_sample(metrics)
        anomaly = detector.detect(metrics)
        
        data = {
            'metrics': metrics,
            'anomaly': None,  # Don't send anomaly every time
            'is_trained': detector.is_trained,
            'baseline': detector.baseline_stats if detector.is_trained else None,
            'sample_count': detector.sample_count,
            'learning_period': detector.learning_period
        }
        
        # Anomaly detection disabled - only count them silently
        if anomaly:
            current_time = time.time()
            if current_time - last_anomaly_time > 30:  # 30 second cooldown
                anomaly_history.append(anomaly)
                # Don't send anomaly to frontend - just count it
                # data['anomaly'] = anomaly
                data['anomaly_history'] = anomaly_history[-10:]
                last_anomaly_time = current_time
        
        socketio.emit('update', data)
        time.sleep(1)

@socketio.on('connect')
def handle_connect():
    print('Client connected')
    emit('status', {'monitoring': monitoring_active})

@socketio.on('start_monitoring')
def handle_start():
    global monitoring_active
    if not monitoring_active:
        monitoring_active = True
        thread = threading.Thread(target=monitoring_loop, daemon=True)
        thread.start()
        emit('status', {'monitoring': True}, broadcast=True)

@socketio.on('stop_monitoring')
def handle_stop():
    global monitoring_active
    monitoring_active = False
    emit('status', {'monitoring': False}, broadcast=True)

if __name__ == '__main__':
    socketio.run(app, debug=True, host='0.0.0.0', port=5000)
