from flask import Flask, render_template, jsonify, request
from flask_socketio import SocketIO, emit
import threading
import time
import requests
import os
from datetime import datetime
from monitor import ResourceMonitor
from anomaly_detector import AnomalyDetector
from simple_storage import SimpleStorageAnalyzer

app = Flask(__name__)
app.config['SECRET_KEY'] = 'system-monitor-secret'
socketio = SocketIO(app, cors_allowed_origins="*")

GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

monitor = ResourceMonitor()
detector = AnomalyDetector(window_size=100, learning_period=30)
storage = SimpleStorageAnalyzer()
monitoring_active = False
anomaly_history = []
last_anomaly_time = 0

@app.route('/')
def index():
    return render_template('index-premium.html')

@app.route('/api/stats')
def get_stats():
    metrics = monitor.collect_metrics()
    top_processes = monitor.get_top_processes(10)
    
    return jsonify({
        'metrics': metrics,
        'processes': top_processes,
        'is_trained': detector.is_trained,
        'baseline': detector.baseline_stats if detector.is_trained else None,
        'anomaly_count': len(anomaly_history)
    })

@app.route('/api/export', methods=['POST'])
def export_report():
    try:
        data = request.json
        export_type = data.get('type', 'email')
        metrics = monitor.collect_metrics()
        
        report = f"""
ADAPTIVE SYSTEM MONITOR REPORT
Generated: {metrics['timestamp']}

CURRENT STATUS:
- CPU Usage: {metrics['cpu_percent']:.1f}%
- Memory Usage: {metrics['memory_percent']:.1f}%
- CPU Cores: {metrics['cpu_count']}
- Memory: {metrics['memory_used_mb']/1024:.1f} GB / {metrics['memory_total_mb']/1024:.1f} GB

NETWORK ACTIVITY:
- Upload: {metrics['net_sent_mbps']:.2f} MB/s
- Download: {metrics['net_recv_mbps']:.2f} MB/s

DISK I/O:
- Read: {metrics['disk_read_mbps']:.2f} MB/s
- Write: {metrics['disk_write_mbps']:.2f} MB/s

AI MONITORING:
- Model Status: {'Trained' if detector.is_trained else 'Learning'}
- Anomalies Detected: {len(anomaly_history)}
- Prevention Methods: 20 Active

This report was generated by Adaptive System Monitor with AI-powered anomaly detection.
        """
        
        if export_type == 'email':
            email = data.get('email')
            print(f"Would send email to: {email}")
            print(report)
            return jsonify({'message': f'Report sent to {email}', 'success': True})
        
        elif export_type == 'sms':
            phone = data.get('phone')
            print(f"Would send SMS to: {phone}")
            summary = f"System Monitor: CPU {metrics['cpu_percent']:.1f}%, Memory {metrics['memory_percent']:.1f}%, {len(anomaly_history)} anomalies detected"
            print(summary)
            return jsonify({'message': f'SMS sent to {phone}', 'success': True})
            
    except Exception as e:
        print(f"Export error: {e}")
        return jsonify({'message': 'Failed to send report', 'success': False}), 500

@app.route('/api/storage/drives')
def get_drives():
    try:
        drives = storage.get_disk_usage_summary()
        return jsonify({'drives': drives, 'success': True})
    except Exception as e:
        print(f"Storage drives error: {e}")
        return jsonify({'error': str(e), 'success': False}), 500

@app.route('/api/storage/scan', methods=['POST'])
def scan_directory():
    try:
        data = request.json
        path = data.get('path', 'C:\\' if os.name == 'nt' else '/')
        
        def progress_callback(processed, total):
            socketio.emit('scan_progress', {
                'processed': processed,
                'total': total,
                'percent': round((processed / total) * 100, 1)
            })
        
        def run_scan():
            try:
                result = storage.quick_scan(path)
                socketio.emit('scan_complete', {'result': result, 'path': path})
            except Exception as e:
                print(f"Scan error: {e}")
                socketio.emit('scan_error', {'error': str(e)})
        
        thread = threading.Thread(target=run_scan, daemon=True)
        thread.start()
        
        return jsonify({'message': 'Quick scan started', 'success': True})
        
    except Exception as e:
        print(f"Storage scan error: {e}")
        return jsonify({'error': str(e), 'success': False}), 500

@app.route('/api/storage/large-files', methods=['POST'])
def find_large_files():
    try:
        data = request.json
        path = data.get('path', 'C:\\' if os.name == 'nt' else '/')
        min_size_mb = data.get('min_size_mb', 100)
        
        large_files = storage.find_large_files(path, min_size_mb)
        return jsonify({'files': large_files, 'success': True})
        
    except Exception as e:
        print(f"Large files error: {e}")
        return jsonify({'error': str(e), 'success': False}), 500

@app.route('/api/storage/file-types', methods=['POST'])
def analyze_file_types():
    try:
        data = request.json
        path = data.get('path', 'C:\\' if os.name == 'nt' else '/')
        
        return jsonify({
            'file_types': {},
            'success': True,
            'message': 'File type analysis not yet implemented'
        })
        
    except Exception as e:
        print(f"File types error: {e}")
        return jsonify({'error': str(e), 'success': False}), 500

@app.route('/api/storage/duplicates', methods=['POST'])
def find_duplicates():
    try:
        data = request.json
        path = data.get('path', 'C:\\' if os.name == 'nt' else '/')
        
        return jsonify({
            'duplicates': [],
            'success': True,
            'message': 'Duplicate detection not yet implemented'
        })
        
    except Exception as e:
        print(f"Duplicates error: {e}")
        return jsonify({'error': str(e), 'success': False}), 500

@app.route('/api/storage/cleanup', methods=['POST'])
def cleanup_suggestions():
    try:
        data = request.json
        path = data.get('path', 'C:\\' if os.name == 'nt' else '/')
        
        return jsonify({
            'suggestions': [],
            'success': True,
            'message': 'Cleanup suggestions not yet implemented'
        })
        
    except Exception as e:
        print(f"Cleanup suggestions error: {e}")
        return jsonify({'error': str(e), 'success': False}), 500
@app.route('/api/storage/hyper-scan', methods=['POST'])
def hyper_scan():
    try:
        data = request.json
        path = data.get('path', 'C:\\' if os.name == 'nt' else '/')
        
        scan_id = f"scan_{int(time.time())}"
        
        def run_scan():
            try:
                result = storage.quick_scan(path)
                
                socketio.emit('hyper_scan_complete', {
                    'scan_id': scan_id,
                    'result': result,
                    'path': path
                })
                
            except Exception as e:
                print(f"Scan error: {e}")
                socketio.emit('hyper_scan_error', {
                    'scan_id': scan_id,
                    'error': str(e)
                })
        
        thread = threading.Thread(target=run_scan, daemon=True)
        thread.start()
        
        return jsonify({
            'message': 'Scan initiated',
            'scan_id': scan_id,
            'success': True
        })
        
    except Exception as e:
        print(f"Scan initialization error: {e}")
        return jsonify({'error': str(e), 'success': False}), 500

@app.route('/api/storage/ultimate-dashboard')
def ultimate_dashboard():
    try:
        drives = storage.get_disk_usage_summary()
        
        return jsonify({
            'drives': drives,
            'success': True
        })
        
    except Exception as e:
        print(f"Dashboard error: {e}")
        return jsonify({'error': str(e), 'success': False}), 500
@app.route('/api/chat', methods=['POST'])
def chat():
    try:
        data = request.json
        user_message = data.get('message', '')
        context = data.get('context', '')
        
        if not GROQ_API_KEY:
            return jsonify({
                'response': 'Chat service is not configured. Please set GROQ_API_KEY.',
                'success': False
            }), 200
        
        headers = {
            'Authorization': f'Bearer {GROQ_API_KEY}',
            'Content-Type': 'application/json'
        }
        
        payload = {
            'model': 'mixtral-8x7b-32768',
            'messages': [
                {
                    'role': 'system',
                    'content': f'You are a helpful system monitoring assistant. {context}. Provide concise, helpful responses about system performance.'
                },
                {
                    'role': 'user',
                    'content': user_message
                }
            ],
            'temperature': 0.7,
            'max_tokens': 300
        }
        
        response = requests.post(GROQ_API_URL, headers=headers, json=payload, timeout=15)
        
        if response.status_code == 200:
            result = response.json()
            ai_response = result['choices'][0]['message']['content']
            return jsonify({'response': ai_response, 'success': True})
        else:
            return jsonify({
                'response': 'I apologize, but I am having trouble connecting. Please try again.',
                'success': False
            }), 200
            
    except Exception as e:
        print(f"Chat error: {e}")
        return jsonify({
            'response': 'I encountered an error. Please try asking again.',
            'success': False
        }), 200

def monitoring_loop():
    global monitoring_active, anomaly_history, last_anomaly_time
    
    while monitoring_active:
        metrics = monitor.collect_metrics()
        detector.add_sample(metrics)
        anomaly = detector.detect(metrics)
        
        data = {
            'metrics': metrics,
            'anomaly': None,
            'is_trained': detector.is_trained,
            'baseline': detector.baseline_stats if detector.is_trained else None,
            'sample_count': detector.sample_count,
            'learning_period': detector.learning_period
        }
        
        if anomaly:
            current_time = time.time()
            if current_time - last_anomaly_time > 30:
                anomaly_history.append(anomaly)
                data['anomaly_history'] = anomaly_history[-10:]
                last_anomaly_time = current_time
        
        socketio.emit('update', data)
        time.sleep(1)

@socketio.on('connect')
def handle_connect():
    print('Client connected')
    emit('status', {'monitoring': monitoring_active})

@socketio.on('start_monitoring')
def handle_start():
    global monitoring_active
    if not monitoring_active:
        monitoring_active = True
        thread = threading.Thread(target=monitoring_loop, daemon=True)
        thread.start()
        emit('status', {'monitoring': True}, broadcast=True)

@socketio.on('stop_monitoring')
def handle_stop():
    global monitoring_active
    monitoring_active = False
    emit('status', {'monitoring': False}, broadcast=True)

if __name__ == '__main__':
    socketio.run(app, debug=True, host='0.0.0.0', port=5000)
